### ISSUE TITLE
Implement missing endpoints in Domains API

### ISSUE THREAD

**Issue by FrontEndCoffee** [sandwave-io/realtimeregister-php#1]
The following endpoints are missing from the DomainsApi. These need to be implemented:
* https://dm.realtimeregister.com/docs/api/domains/update
* https://dm.realtimeregister.com/docs/api/domains/transfer
* https://dm.realtimeregister.com/docs/api/domains/pushtransfer
* https://dm.realtimeregister.com/docs/api/domains/transferinfo
* https://dm.realtimeregister.com/docs/api/domains/renew
* https://dm.realtimeregister.com/docs/api/domains/restore
* https://dm.realtimeregister.com/docs/api/domains/delete
* https://dm.realtimeregister.com/docs/api/domains/zoneinfo
* https://dm.realtimeregister.com/docs/api/domains/zoneupdate

**Comment by markdingemanse** [comment]
Additional endoints needed:
