### ISSUE TITLE
Implement Financial API

### ISSUE THREAD

**Issue by FrontEndCoffee** [sandwave-io/realtimeregister-php#13]
Documentation: https://dm.realtimeregister.com/docs/api/financial

**Module:**

- [ ] Add a `FinancialApi` module in the `Api` namespace
- [ ] Add this module to the `RealtimeRegister` class.

**Endpoints:**

- [ ] Get transaction
- [ ] List transactions
- [ ] Get exchange rates

When implementing the endpoints, make sure to include links to the documentation using the `@see` annotation in docblocks.

**Tests:**

- [ ] Add tests for all the added domain objects
- [ ] Add tests for all the added endpoints

**Comment by zaratedev** [comment]
Hey, I'll want work on this issues for the hacktoberfest challenge.

**Comment by FrontEndCoffee** [comment]
Great! If you have any questions about the codebase, feel free to ask 😁
