### ISSUE TITLE
Request Logging

### ISSUE THREAD

**Issue by markdingemanse** [sandwave-io/realtimeregister-php#2]
I would like to see a feature when i am in a debugging state i have the option to see what payload was send to the remote api. You should be able to provide the client constructor with an optional PSR-Log service that can log this payload when a remote call is being executed.

**Comment by FrontEndCoffee** [comment]
I would suggest an implementation where the constructors of the service/client take an optional `Psr\LoggerInterface`, if this interface is set, the `AuthorizedClient` should log the sent request and received response to `LoggerInterface::debug()`. 

Optionally the http method and endpoint could also be provided within the $context array as second argument of `LoggerInterface::debug()`.
