### ISSUE TITLE
Implement Providers API

### ISSUE THREAD

**Issue by FrontEndCoffee** [sandwave-io/realtimeregister-php#9]
Documentation: https://dm.realtimeregister.com/docs/api/providers

**Module:**

- [ ] Add a `ProvidersApi` module in the `Api` namespace
- [ ] Add this module to the `RealtimeRegister` class.

**Endpoints:**

- [ ] Get
- [ ] List
- [ ] Get downtime
- [ ] List downtime

When implementing the endpoints, make sure to include links to the documentation using the `@see` annotation in docblocks.

**Tests:**

- [ ] Add tests for all the added domain objects
- [ ] Add tests for all the added endpoints

**Comment by TanoRojas** [comment]
@FrontEndCoffee Hello! I would like to work on this issue. Let me know if it is still available. Thanks!

**Comment by FrontEndCoffee** [comment]
@TanoRojas It is still available, I'm looking forward to your pull request!
